#! /bin/bash
#PBS -q mri2020
#PBS -N QCNN
#PBS -l select=1:ncpus=64:mpiprocs=64:mem=40gb
#PBS -l walltime=120:00:00
#PBS -o stdout.txt
#PBS -e stderr.txt
cd $PBS_O_WORKDIR

module load gcc/9.5.0
module load openmpi/4.1.3-gcc/9.5.0-ucx
module load boost/1.79.0-gcc/9.5.0-nompi
export OMP_NUM_THREADS=1

mpirun ./hybrid param > log1.txt
